# Generated by Django 6.0.6 on 2026-06-24 20:12

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='اسم المهنّئ')),
                ('message', models.TextField(max_length=500, verbose_name='نص التهنئة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], db_index=True, default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'تهنئة',
                'verbose_name_plural': 'التهاني',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeddingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groom_name', models.CharField(default='محمود', max_length=60, verbose_name='اسم العريس')),
                ('bride_name', models.CharField(default='رينان', max_length=60, verbose_name='اسم العروس')),
                ('wedding_datetime', models.DateTimeField(default=core.models.default_wedding_datetime, verbose_name='موعد الزفاف (يُخزَّن بتوقيت القاهرة)')),
                ('venue_name', models.CharField(blank=True, max_length=120, verbose_name='اسم القاعة')),
                ('venue_address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('map_url', models.URLField(blank=True, verbose_name='رابط الخريطة')),
                ('hijri_text', models.CharField(blank=True, max_length=60, verbose_name='التاريخ الهجري (يدوي)')),
            ],
            options={
                'verbose_name': 'إعدادات الزفاف',
                'verbose_name_plural': 'إعدادات الزفاف',
            },
        ),
    ]
