# Generated by Django 6.0.6 on 2026-06-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_weddingconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingconfig',
            name='bride_father',
            field=models.CharField(default='الشريف فلان الفولاني', max_length=160, verbose_name='والد العروس'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='groom_father',
            field=models.CharField(default='رجل الأعمال السيّد سمير محمود الزنط (أبو إبراهيم)', max_length=160, verbose_name='والد العريس'),
        ),
    ]
