# Generated by Django 6.0.6 on 2026-06-25 10:51

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_weddingconfig_bride_father_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreetingSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.TextField(max_length=300, verbose_name='نص التهنئة')),
                ('category', models.CharField(blank=True, choices=[('religious', 'ديني'), ('family', 'عائلي'), ('short', 'قصير'), ('formal', 'رسمي'), ('nice', 'جميل')], max_length=15, verbose_name='الفئة')),
                ('active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('sequence', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'تهنئة جاهزة',
                'verbose_name_plural': 'التهاني الجاهزة',
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WeddingGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(blank=True, max_length=30, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('group', models.CharField(choices=[('groom_family', 'عائلة العريس'), ('bride_family', 'عائلة العروس'), ('friends', 'أصدقاء'), ('colleagues', 'زملاء'), ('general', 'ضيوف عامون')], db_index=True, default='general', max_length=20, verbose_name='المجموعة')),
                ('guest_count', models.PositiveSmallIntegerField(default=1, verbose_name='عدد الأفراد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('invitation_token', models.CharField(default=core.models.generate_invitation_token, editable=False, max_length=32, unique=True)),
                ('invitation_status', models.CharField(choices=[('draft', 'مسودة'), ('ready', 'جاهزة'), ('sent_whatsapp', 'أُرسلت عبر واتساب'), ('sent_email', 'أُرسلت عبر البريد'), ('opened', 'فُتحت'), ('greeted', 'كتب تهنئة')], db_index=True, default='draft', max_length=15, verbose_name='الحالة')),
                ('last_opened_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر فتح')),
                ('invited_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإرسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مدعو',
                'verbose_name_plural': 'المدعوون',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddField(
            model_name='greeting',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='greeting',
            name='country_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='bride_family_name_ar',
            field=models.CharField(blank=True, max_length=80, verbose_name='عائلة العروس'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='default_email_body_template',
            field=models.TextField(blank=True, default='السلام عليكم ورحمة الله،\n\n{{ guest_name }} الكريم،\nيتشرّف أهل العروسين بدعوتكم لحضور حفل زفاف {{ groom_name }} و{{ bride_name }} يوم {{ wedding_date }}{{ venue_name }}.\n\nتفضّلوا بفتح دعوتكم الخاصة من الرابط التالي:\n{{ invitation_link }}\n\nبانتظار تشريفكم،', verbose_name='قالب بريد الدعوة'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='default_email_subject',
            field=models.CharField(blank=True, default='دعوة حفل زفاف {{ groom_name }} و{{ bride_name }}', max_length=200, verbose_name='عنوان بريد الدعوة'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='default_whatsapp_message_template',
            field=models.TextField(blank=True, default='السلام عليكم {{ guest_name }} 🤍\nيسعدنا دعوتكم لحضور حفل زفاف {{ groom_name }} و{{ bride_name }} يوم {{ wedding_date }}{{ venue_name }}.\nهذه دعوتكم الخاصة: {{ invitation_link }}', verbose_name='قالب رسالة واتساب'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='groom_family_name_ar',
            field=models.CharField(blank=True, default='الزنط', max_length=80, verbose_name='عائلة العريس'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='invitation_intro_text',
            field=models.TextField(blank=True, default='يتشرّفان بدعوتكم لمشاركتهما فرحة العمر', verbose_name='نص الدعوة (سطر تمهيدي)'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='privacy_notice_short',
            field=models.TextField(blank=True, default='تُستخدم بياناتكم (الاسم ورقم الهاتف والبريد إن وُجد) فقط لإدارة دعوات الزفاف والتهاني. لا يُعرَض الهاتف أو البريد أو عنوان الـIP للعامة. يُستخدم الـIP داخلياً للمراجعة وقد يُستعمل لتحديد الدولة فقط. يمكنكم طلب حذف تهنئتكم أو بيانات دعوتكم بالتواصل مع المسؤول.', verbose_name='إشعار الخصوصية المختصر'),
        ),
        migrations.AddField(
            model_name='greeting',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greetings', to='core.weddingguest'),
        ),
    ]
