# Generated by Django 6.0.6 on 2026-06-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_seed_greeting_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='greeting',
            name='card_template',
            field=models.CharField(choices=[('no_photo_minimal', 'بدون صورة — راقٍ'), ('photo_story', 'ستوري بالصورة'), ('photo_frame', 'إطار أنيق'), ('family_warm', 'عائلي دافئ'), ('palestinian_soft', 'لمسة فلسطينية'), ('cairo_evening', 'غروب القاهرة')], default='no_photo_minimal', max_length=20, verbose_name='قالب البطاقة'),
        ),
        migrations.AddField(
            model_name='greeting',
            name='photo_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='greetings/thumbs/'),
        ),
        migrations.AddField(
            model_name='greeting',
            name='uploaded_photo',
            field=models.ImageField(blank=True, null=True, upload_to='greetings/cards/', verbose_name='الصورة'),
        ),
    ]
