# Generated by Django 6.0.6 on 2026-06-25 13:13

from django.db import migrations, models


def publish_pending(apps, schema_editor):
    """Switch to post-moderation: any legacy 'pending' greeting becomes visible."""
    Greeting = apps.get_model('core', 'Greeting')
    for g in Greeting.objects.filter(status='pending'):
        g.status = 'approved'
        if g.approved_at is None:
            g.approved_at = g.created_at
        g.save(update_fields=['status', 'approved_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_greeting_card_template_greeting_photo_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='greeting',
            name='status',
            field=models.CharField(choices=[('pending', 'بانتظار'), ('approved', 'ظاهرة'), ('rejected', 'محظورة')], db_index=True, default='approved', max_length=10),
        ),
        migrations.RunPython(publish_pending, migrations.RunPython.noop),
    ]
