# Generated by Django 6.0.6 on 2026-07-06 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_greeting_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='عند الإيقاف: وضع آمن — لا يُرسَل شيء فعلياً، يُسجَّل «سيُرسَل» فقط.', verbose_name='تفعيل الإرسال الحيّ')),
                ('phone_number_id', models.CharField(blank=True, max_length=40, verbose_name='Phone Number ID')),
                ('waba_id', models.CharField(blank=True, max_length=40, verbose_name='WhatsApp Business Account ID')),
                ('default_template_name', models.CharField(blank=True, max_length=100, verbose_name='اسم القالب الافتراضي')),
                ('template_lang', models.CharField(default='ar', max_length=10, verbose_name='لغة القالب')),
                ('default_country_code', models.CharField(default='20', help_text='لتطبيع الأرقام المحلية (مصر=20).', max_length=4, verbose_name='رمز الدولة الافتراضي')),
                ('test_recipient', models.CharField(blank=True, max_length=30, verbose_name='رقم اختبار الإرسال')),
            ],
            options={
                'verbose_name': 'إعدادات واتساب',
                'verbose_name_plural': 'إعدادات واتساب',
            },
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='سُلّمت في'),
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_guests', to=settings.AUTH_USER_MODEL, verbose_name='دعاه'),
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر إرسال'),
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='phone_e164',
            field=models.CharField(blank=True, db_index=True, max_length=20, verbose_name='الرقم المُطبَّع'),
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='قُرئت في'),
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='send_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد مرات الإرسال'),
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='wa_message_id',
            field=models.CharField(blank=True, max_length=128, verbose_name='معرّف رسالة واتساب'),
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='wa_status',
            field=models.CharField(choices=[('none', '—'), ('queued', 'بالانتظار'), ('sent', 'أُرسلت'), ('delivered', 'سُلّمت'), ('read', 'قُرئت'), ('failed', 'فشلت')], db_index=True, default='none', max_length=10, verbose_name='حالة واتساب'),
        ),
        migrations.CreateModel(
            name='InviterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=80, verbose_name='الاسم الظاهر')),
                ('side', models.CharField(choices=[('groom', 'أهل العريس'), ('bride', 'أهل العروس'), ('both', 'الطرفان')], default='both', max_length=10, verbose_name='الجهة')),
                ('can_view_all', models.BooleanField(default=False, verbose_name='يرى كل المدعوين')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='هاتف (اختياري)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inviter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'مُرسِل (عائلة)',
                'verbose_name_plural': 'المُرسِلون (العائلة)',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=100)),
                ('wa_message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('status', models.CharField(choices=[('none', '—'), ('queued', 'بالانتظار'), ('sent', 'أُرسلت'), ('delivered', 'سُلّمت'), ('read', 'قُرئت'), ('failed', 'فشلت')], default='queued', max_length=12)),
                ('error', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message_logs', to='core.weddingguest')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل رسالة',
                'verbose_name_plural': 'سجل الرسائل',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القالب في Meta')),
                ('language', models.CharField(default='ar', max_length=10, verbose_name='اللغة')),
                ('category', models.CharField(choices=[('utility', 'Utility (أرخص)'), ('marketing', 'Marketing')], default='utility', max_length=12, verbose_name='الفئة')),
                ('body_preview_ar', models.TextField(blank=True, verbose_name='نص المعاينة (عربي)')),
                ('variables_map', models.JSONField(blank=True, default=list, verbose_name='خريطة المتغيّرات')),
                ('is_approved', models.BooleanField(default=False, verbose_name='معتمد من Meta')),
                ('active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'قالب واتساب',
                'verbose_name_plural': 'قوالب واتساب',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'language'), name='uniq_watemplate_name_lang')],
            },
        ),
    ]
