# Generated by Django 6.0.6 on 2026-07-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_whatsappconfig_weddingguest_delivered_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingconfig',
            name='privacy_notice_short',
            field=models.TextField(blank=True, default='تُستخدم بياناتكم (الاسم ورقم الهاتف والبريد إن وُجد) فقط لإدارة دعوات الزفاف والتهاني. تُرسَل الدعوات عبر واتساب، فيُشارَك رقمكم مع خدمة WhatsApp (Meta) لتوصيل الرسالة فقط. لا يُعرَض الهاتف أو البريد أو عنوان الـIP للعامة. يُستخدم الـIP داخلياً للمراجعة وقد يُستعمل لتحديد الدولة فقط. يمكنكم طلب حذف تهنئتكم أو بيانات دعوتكم بالتواصل مع المسؤول.', verbose_name='إشعار الخصوصية المختصر'),
        ),
    ]
