# Generated by Django 6.0.6 on 2026-07-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_twilio_template_bodies'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingconfig',
            name='greeting_cta_label',
            field=models.CharField(blank=True, default='اكتب تهنئتك', max_length=60, verbose_name='زرّ كتابة التهنئة'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='rsvp_attend_label',
            field=models.CharField(blank=True, default='سأحضر بإذن الله', max_length=60, verbose_name='زرّ التأكيد'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='rsvp_decline_label',
            field=models.CharField(blank=True, default='أعتذر مع خالص المحبّة', max_length=60, verbose_name='زرّ الاعتذار'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='rsvp_enabled',
            field=models.BooleanField(default=True, help_text='إظهار زرَّي «تأكيد الحضور / الاعتذار» على صفحة الدعوة الخاصة.', verbose_name='تفعيل تأكيد الحضور'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='rsvp_prompt',
            field=models.CharField(blank=True, default='هل تتشرّفون بمشاركتنا فرحتنا؟', max_length=160, verbose_name='سؤال الحضور'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='rsvp_thanks_attending',
            field=models.CharField(blank=True, default='سعِدنا بتأكيدكم 🤍 بانتظار طلّتكم البهيّة.', max_length=200, verbose_name='ردّ بعد التأكيد'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='rsvp_thanks_declined',
            field=models.CharField(blank=True, default='نتفهّم ظروفكم الكريمة، وتبقون في القلب 🤍', max_length=200, verbose_name='ردّ بعد الاعتذار'),
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='rsvp',
            field=models.CharField(choices=[('none', 'بلا ردّ'), ('attending', 'سيحضر'), ('declined', 'اعتذر')], db_index=True, default='none', max_length=10, verbose_name='الحضور'),
        ),
        migrations.AddField(
            model_name='weddingguest',
            name='rsvp_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ردّ الحضور في'),
        ),
    ]
