# Generated by Django 6.0.6 on 2026-07-09 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_backfill_guest_phone_e164'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='أيقونة تبويب المتصفّح. إن تُركت فارغة يُستخدم الشعار. صورة مربّعة يُفضّل.', null=True, upload_to='site/', verbose_name='أيقونة المتصفّح (Favicon)'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='خلفية الصفحة الرئيسية والظرف. إن تُركت فارغة تُستخدم الصورة الافتراضية.', null=True, upload_to='site/', verbose_name='صورة الخلفية الرئيسية'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='logo',
            field=models.ImageField(blank=True, help_text='يظهر أعلى الصفحة الرئيسية وفي ترويسة اللوحة بدل اسمَي العروسين. PNG بخلفية شفّافة يُفضّل.', null=True, upload_to='site/', verbose_name='شعار الموقع'),
        ),
    ]
