# Generated by Django 6.0.6 on 2026-07-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_weddingconfig_favicon_weddingconfig_hero_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingconfig',
            name='og_image',
            field=models.ImageField(blank=True, help_text='الصورة التي تظهر عند مشاركة رابط الموقع على واتساب/فيسبوك. 1200×630 بكسل يُفضّل. إن تُركت فارغة تُستخدم الصورة المولّدة تلقائياً.', null=True, upload_to='site/', verbose_name='صورة المشاركة (OG)'),
        ),
    ]
