# Generated by Django 6.0.6 on 2026-07-09 08:13

from django.db import migrations, models

_OLD_INTRO = "يتشرّفان بدعوتكم لمشاركتهما فرحة العمر"
_NEW_INTRO = "بدعوتكم لحضور حفل زفاف أبنائهما"


def reword_intro(apps, schema_editor):
    """The intro line is now rendered AFTER the fathers' names, so a row still
    holding the old default wording would read ungrammatically. Only rows the
    operator never customized (== old default) are rewritten."""
    WeddingConfig = apps.get_model("core", "WeddingConfig")
    WeddingConfig.objects.filter(invitation_intro_text=_OLD_INTRO).update(
        invitation_intro_text=_NEW_INTRO)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_weddingconfig_og_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weddingconfig',
            name='bride_family_name_ar',
        ),
        migrations.RemoveField(
            model_name='weddingconfig',
            name='groom_family_name_ar',
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='couple_names_latin',
            field=models.CharField(blank=True, default='Mahmoud & Rinan', help_text='يظهر في تذييل الموقع. اتركه فارغاً لإخفائه.', max_length=120, verbose_name='اسما العروسين باللاتينية'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='invitation_page_intro',
            field=models.CharField(blank=True, default='يتشرّف والداهما بدعوتكم لحضور حفل زفاف', help_text='السطر الذي يسبق اسمَي العروسين في صفحة الدعوة الخاصة /i/…', max_length=200, verbose_name='تمهيد صفحة الدعوة الخاصة'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='masthead_text',
            field=models.CharField(default='أفراح آل الزنط', help_text='يظهر أعلى الصفحة الرئيسية، مثل: أفراح آل الزنط.', max_length=120, verbose_name='سطر العائلة (أعلى الدعوة)'),
        ),
        migrations.AddField(
            model_name='weddingconfig',
            name='seo_description',
            field=models.CharField(blank=True, help_text='يظهر في نتائج البحث ومعاينات المشاركة. إن تُرك فارغاً يُستخدم نص تلقائي بأسماء العروسين.', max_length=200, verbose_name='وصف الموقع (لمحرّكات البحث والمشاركة)'),
        ),
        migrations.AlterField(
            model_name='greetingsuggestion',
            name='category',
            field=models.CharField(blank=True, choices=[('religious', 'ديني'), ('family', 'عائلي'), ('short', 'قصير'), ('formal', 'رسمي'), ('nice', 'جميل')], help_text='للتنظيم داخل لوحة الإدارة فقط — الزوّار يرون أول ١٠ تهانٍ مفعّلة حسب الترتيب، بلا تصنيف.', max_length=15, verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='weddingconfig',
            name='invitation_intro_text',
            field=models.TextField(blank=True, default='بدعوتكم لحضور حفل زفاف أبنائهما', help_text='يظهر في الصفحة الرئيسية بعد «يتشرّف + اسمَي الوالدين».', verbose_name='نص الدعوة (بعد اسمَي الوالدين)'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='variables_map',
            field=models.JSONField(blank=True, default=list, help_text='للعرض فقط — الترتيب الفعلي ثابت في الكود: 1=اسم الضيف، 2=الموقع، 3=رابط الدعوة، 4=رمز الدعوة.', verbose_name='خريطة المتغيّرات (للتوثيق فقط)'),
        ),
        migrations.RunPython(reword_intro, migrations.RunPython.noop),
    ]
