# Generated by Django 6.0.6 on 2026-07-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_weddingconfig_bride_family_name_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingguest',
            name='time_on_site_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='مدة التصفح (ثوانٍ)'),
        ),
    ]
