from django.conf import settings
from django.templatetags.static import static

from .models import WeddingConfig


def _og(config):
    """Share (OG) image path + dimensions — never raises.

    Order: admin upload → generated og-image.jpg → tracked hero-bg.jpg → "".
    og-image.jpg is generated (gitignored), so under production manifest
    storage `static()` RAISES if `npm run assets:build` wasn't run before
    collectstatic — and this processor runs on EVERY request, which would
    500 the whole site. Degrade instead of dying.

    Dimensions are emitted only for the bundled assets (known sizes); an
    admin-uploaded image has unknown dimensions and the hints are optional.
    """
    if config.og_image:
        return config.og_image.url, None, None
    for candidate, w, h in (("img/og-image.jpg", 1200, 630), ("img/hero-bg.jpg", 1600, 900)):
        try:
            return static(candidate), w, h
        except Exception:
            continue
    return "", None, None


def _hero(config):
    """Hero artwork src + optional responsive srcset — never raises.

    The mobile/desktop variants are generated by `npm run assets:build`
    (gitignored, like og-image.jpg), so under manifest storage they may be
    absent — degrade to the single tracked source instead of 500ing.
    An admin-uploaded hero has no variants; it is served as-is.
    """
    if config.hero_image:
        return config.hero_image.url, ""
    try:
        src = static("img/hero-bg.jpg")
    except Exception:
        return "", ""
    parts = []
    for candidate, w in (("img/hero-720.jpg", 720), ("img/hero-1080.jpg", 1080)):
        try:
            parts.append(f"{static(candidate)} {w}w")
        except Exception:
            continue
    if parts:
        parts.append(f"{src} 1600w")
    return src, ", ".join(parts)


def _favicon(config):
    """Favicon URL: admin upload → logo → generated fallback icon → "".

    Same manifest-safety rule as the other generated assets: favicon.png is
    produced by `npm run assets:build` (gitignored), so degrade instead of
    raising on every request.
    """
    if config.favicon:
        return config.favicon.url
    if config.logo:
        return config.logo.url
    try:
        return static("img/favicon.png")
    except Exception:
        return ""


def wedding(request):
    """Expose the wedding config and Open Graph helpers to every template."""
    site_url = settings.SITE_URL.rstrip("/")
    config = WeddingConfig.get()
    og_path, og_w, og_h = _og(config)
    hero_src, hero_srcset = _hero(config)
    return {
        "config": config,
        "site_url": site_url,
        # Bare display domain for footers/cards/og:site_name (e.g. "elzant.com").
        "site_domain": site_url.split("//")[-1].split("/")[0],
        "canonical_url": f"{site_url}{request.path}",
        "og_image": f"{site_url}{og_path}" if og_path else "",
        "og_image_width": og_w,
        "og_image_height": og_h,
        "hero_src": hero_src,
        "hero_srcset": hero_srcset,
        "favicon_url": _favicon(config),
    }
